---
abstract: 'Build and make available ODE library - L<http://ode.org/>'
author:
  - 'KMX <kmx@cpan.org>'
build_requires:
  Archive::Extract: 0
  Archive::Tar: 0
  Digest::SHA: 0
  File::Copy: 0
  File::Fetch: 0
  File::Find: 0
  File::Path: 2.07
  File::ShareDir: 0
  File::Spec: 0
  Module::Build: 0.36
configure_requires:
  Archive::Extract: 0
  Digest::SHA: 0
  File::Copy: 0
  File::Fetch: 0
  File::Find: 0
  File::Path: 2.07
  File::Spec: 0
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-ODE
provides:
  Alien::ODE:
    file: lib/Alien/ODE.pm
    version: 1.0
requires:
  File::ShareDir: 1.00
  File::Spec: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Alien-ODE
  license: http://dev.perl.org/licenses/
  repository: http://github.com/kthakore/Alien_ODE
version: 1.0
